name: Build

on: [push, pull_request]

jobs:
    MSVC:
        runs-on: windows-2022

        name: Windows MSVC

        steps:
          - uses: actions/checkout@v4
          - uses: ilammy/msvc-dev-cmd@v1
            with:
              arch: amd64
          - uses: xmake-io/github-action-setup-xmake@v1
            with:
              xmake-version: v3.0.0
              actions-cache-folder: '.xmake-cache'
              actions-cache-key: "windows-2022"
              package-cache: true
              package-cache-key: "windows-2022"
              build-cache: true
              build-cache-key: "windows-2022-release"

          - name: Configure
            run: |
              xmake config --yes -m release --toolchain=msvc

          - name: Build
            run: |
              xmake build --verbose --diagnosis --all

          - name: Test
            run: xmake test --verbose

          - name: Benchmark
            run: xmake run --verbose eirin_fixed.benchmark
          
          - name: Benchmark (For Compare)
            run: xmake run --verbose double.benchmark

    ClangCl:
        runs-on: windows-2025

        name: Windows Clang-Cl

        steps:
          - uses: actions/checkout@v4

          - uses: xmake-io/github-action-setup-xmake@v1
            with:
              xmake-version: v3.0.0
              actions-cache-folder: '.xmake-cache'
              actions-cache-key: "windows-2025"
              package-cache: true
              package-cache-key: "windows-2025"
              build-cache: true
              build-cache-key: "windows-2025-release"

          - name: Configure
            run: |
              xmake config --yes -m release --toolchain=clang-cl

          - name: Build
            run: |
              xmake build --verbose --diagnosis --all

          - name: Test
            run: xmake test --verbose

          - name: Benchmark
            run: xmake run --verbose eirin_fixed.benchmark
          
          - name: Benchmark (For Compare)
            run: xmake run --verbose double.benchmark

    Clang:
        runs-on: ubuntu-24.04

        strategy:
          matrix:
            clang: [15, 18]
          fail-fast: false
        name: Linux Clang ${{ matrix.clang }}

        steps:
          - name: Install Dependencies
            run: |
              sudo apt-get update
              sudo apt-get install -y cmake ninja-build clang-${{ matrix.clang }} clang++-${{ matrix.clang }}

          - uses: actions/checkout@v4
          - uses: xmake-io/github-action-setup-xmake@v1
            with:
              xmake-version: v3.0.0
              actions-cache-folder: '.xmake-cache'
              actions-cache-key: "linux-clang"
              package-cache: true
              package-cache-key: "linux-clang"
              build-cache: true
              build-cache-key: "linux-clang"

          - name: Configure
            run: |
              xmake config --yes -m release --toolchain=clang-${{ matrix.clang }}

          - name: Build
            run: |
              xmake build --verbose --diagnosis --all

          - name: Test
            run: xmake test --verbose

          - name: Benchmark
            run: xmake run --verbose eirin_fixed.benchmark
          
          - name: Benchmark (For Compare)
            run: xmake run --verbose double.benchmark

    GCC:
        runs-on: ubuntu-24.04

        strategy:
          matrix:
            gcc: [13, 14]
          fail-fast: false
        name: Linux GCC ${{ matrix.gcc }}

        steps:
          - name: Install Dependencies
            run: |
              sudo apt-get update
              sudo apt-get install -y cmake ninja-build gcc-${{ matrix.gcc }} g++-${{ matrix.gcc }}

          - uses: actions/checkout@v4
          - uses: xmake-io/github-action-setup-xmake@v1
            with:
              xmake-version: v3.0.0
              actions-cache-folder: '.xmake-cache'
              actions-cache-key: "linux-gcc"
              package-cache: true
              package-cache-key: "linux-gcc"
              build-cache: true
              build-cache-key: "linux-gcc"

          - name: Configure
            run: |
              xmake config --yes -m release --toolchain=gcc-${{ matrix.gcc }}

          - name: Build
            run: |
              xmake build --verbose --diagnosis --all

          - name: Test
            run: xmake test --verbose

          - name: Benchmark
            run: xmake run --verbose eirin_fixed.benchmark
          
          - name: Benchmark (For Compare)
            run: xmake run --verbose double.benchmark

    Emscripten:
        runs-on: ubuntu-24.04

        name: Emscripten

        steps:
          - name: Install Dependencies
            run: |
              sudo apt-get update
              sudo apt-get install -y cmake ninja-build

          - uses: actions/checkout@v4
          - uses: xmake-io/github-action-setup-xmake@v1
            with:
              xmake-version: v3.0.0
              actions-cache-folder: '.xmake-cache'
              actions-cache-key: "wasm"
              package-cache: true
              package-cache-key: "wasm"
              build-cache: true
              build-cache-key: "wasm"

          - name: Setup emsdk
            uses: mymindstorm/setup-emsdk@v14
            with:
              actions-cache-folder: emsdk-cache

          - name: Configure
            run: |
              xmake config --yes -m release -p wasm

          - name: Build
            run: |
              xmake build --verbose --diagnosis --all

          - name: Test
            run: node build/wasm/wasm32/release/eirin_fixed.test.js

          - name: Benchmark
            run: node build/wasm/wasm32/release/eirin_fixed.benchmark.js
          
          - name: Benchmark (For Compare)
            run: node build/wasm/wasm32/release/double.benchmark.js
